using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RobustArithmetic.Test
{
    class TriangulationTests
    {
        /*
         
         * 
         * I have passed on following points to this algorithum,seems its generating atleast one less vertex and one less edge. I have compared voronoi diagram generated by these points wih standard GIS software like MapInfo, is it the thing that you need to address ?
 
1 399380.8371	-5526801.89
2 400882.095	-5525038.395
3 402256.1277	-5524122.657
4 399247.2089	-5525471.661
5 401383.9145	-5523790.174
         * 
         * 
         * NODE_ID	EASTING	 NORTHING
6	10494.00016	10092.53629
7	10290.7531	10684.97519
8	9947.773702	11043.95948
9	9776.284008	11059.26798
10	10991.95541	10217.30055
11	10057.01902	10092.5363
 
It gives 8 edges and 3 vertex, but due to wrong location of vertex 3, egde no 6,7 and 8 have not come out properly. Actual location of vertex 3 should be 9819.40,10578.40. I strongly feel that it should have 4 vertexes. 
 
         * 
         * */
    }
}
